# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_frame(object):
    def setupUi(self, login_frame):
        login_frame.setObjectName("login_frame")
        login_frame.resize(640, 499)
        self.centralwidget = QtWidgets.QWidget(login_frame)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 170, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 230, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.username_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.username_txt.setGeometry(QtCore.QRect(290, 170, 131, 31))
        self.username_txt.setObjectName("username_txt")
        self.password_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.password_txt.setGeometry(QtCore.QRect(290, 220, 131, 31))
        self.password_txt.setObjectName("password_txt")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 290, 111, 41))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(490, 30, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(490, 60, 55, 16))
        self.label_4.setObjectName("label_4")
        login_frame.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(login_frame)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 26))
        self.menubar.setObjectName("menubar")
        login_frame.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(login_frame)
        self.statusbar.setObjectName("statusbar")
        login_frame.setStatusBar(self.statusbar)

        self.retranslateUi(login_frame)
        QtCore.QMetaObject.connectSlotsByName(login_frame)

    def retranslateUi(self, login_frame):
        _translate = QtCore.QCoreApplication.translate
        login_frame.setWindowTitle(_translate("login_frame", "Login"))
        self.label.setText(_translate("login_frame", "Username:"))
        self.label_2.setText(_translate("login_frame", "Password:"))
        self.username_txt.setText(_translate("login_frame", "admin"))
        self.password_txt.setText(_translate("login_frame", "admin123"))
        self.pushButton.setText(_translate("login_frame", "Login"))
        self.label_3.setText(_translate("login_frame", "admin"))
        self.label_4.setText(_translate("login_frame", "admin123"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_frame = QtWidgets.QMainWindow()
    ui = Ui_login_frame()
    ui.setupUi(login_frame)
    login_frame.show()
    sys.exit(app.exec_())
